---
title: "5e spell stats"
author: "Eberardo B. Raymundo"
date: "2024-09-25"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::knit_hooks$set(time_it = local({
	now <- NULL
	
	function(before, options) {
		if (before) {
		# record the current time before each chunk
			now <<- Sys.time()
	    } 
		else {
			# calculate the time difference after a chunk
			result <- difftime(Sys.time(), now, units = "secs")
			# return a character string to show the time
			paste("Chunk runtime:", round(result, 3), "seconds")
	    }
	}
}))

knitr::opts_chunk$set(time_it = TRUE)
```


```{r libraries, message = FALSE}
library(dplyr)
library(ggplot2)
```


```{r connection}
connection <- DBI::dbConnect(RSQLite::SQLite(), dbname = "../Gestalt.db")
```


```{r spell data retrieval, message = FALSE}
spell_table <- tbl(connection, "Spell")

spell_data <- spell_table %>% collect()

spell_data <- spell_data %>%
  mutate(concentration = as.logical(concentration)) %>%
  mutate(ritual = as.logical(ritual))
```


```{r school distribution}
spell_data %>%
  ggplot() +
    geom_bar(aes(school, fill = school), show.legend = FALSE) +
    scale_fill_viridis_d() +
    labs(title = "Number of Spells per School") +
    xlab("Spell School") +
    ylab("Spell Count") +
    theme_classic()

ggsave("../images/spells_by_school.png", width = 7, height = 4)
```


```{r level school areas, message = FALSE}
spell_data %>%
  group_by(level, school) %>%
  summarize(count = n()) %>%
  ggplot() +
    geom_area(aes(level, count, fill = school), alpha = 0.8, colour = "black", size = 0.25) +
    scale_x_continuous(breaks = seq(0, 9)) +
    scale_fill_viridis_d() +
    labs(title = "Number of Spells per Level") +
    xlab("Spell Level") +
    ylab("Spell Count") +
    theme_classic()

ggsave("../images/schools_by_level.png", width = 8, height = 4)
```


```{r}
spell_data %>%
  group_by(casting_time) %>%
  summarize(count = n()) %>%
  ggplot() +
    geom_col(aes(casting_time, count), 
             alpha = 0.6, 
             fill = "red", 
             colour = "black", 
             linewidth = 0.1) +
    geom_text(aes(casting_time, count, label = count), vjust = -0.5, size = 3) +
    labs(title = "Number of Spells per Casting Time") +
    xlab("Casting Time") +
    ylab("Spell Count") +
    theme_classic()

ggsave("../images/spells_by_casting_time.png", width = 7, height = 4)
```


```{r}
spell_data %>%
  mutate(trimmed_duration = sub("^Up to ", "", duration)) %>%
  group_by(trimmed_duration) %>%
  ggplot() +
    geom_bar(aes(trimmed_duration, fill = concentration)) +
    coord_flip() +
    labs(title = "Number of Spells per Duration") +
    xlab("Spell Duration") +
    ylab("Spell Count") +
    theme_classic()
```


```{r}
spell_data %>%
  mutate(description_word_count = sapply(strsplit(description, " "), length)) %>%
  ggplot() +
    geom_point(aes(level, description_word_count), position = position_jitter(width = 0.2, height = 0)) +
    scale_x_continuous(breaks = seq(0, 9)) +
    labs(title = "Spell Word Count per Spell Level") +
    xlab("Spell Level") +
    ylab("Word Count") +
    theme_classic()
```


```{r}
spell_data %>%
  mutate(description_word_count = sapply(strsplit(description, " "), length)) %>%
  group_by(level) %>%
  arrange(desc(description_word_count), .by_group = TRUE) %>%
  slice_head(n = 3) %>%
  select(spell_name, level, description_word_count)
```


```{r}
spell_data %>%
  mutate(description_word_count = sapply(strsplit(description, " "), length)) %>%
  group_by(level) %>%
  arrange(description_word_count, .by_group = TRUE) %>%
  slice_head(n = 3) %>%
  select(spell_name, level, description_word_count)
```

